version: '3'

services:

  telvina_server:
    build:
      context: ./telvina_server
      dockerfile: Dockerfile
    container_name: telvina_server

  proxy:
    image: nginx:latest
    container_name: proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080
    depends_on:
      - telvina_server
